### ISSUE TITLE
BSD compatibility

### ISSUE THREAD

**Issue by dbohdan** [nooga/let-go#84]
It would be nice to see let-go build on Free/Net/OpenBSD the way Joker goes, or at least build on FreeBSD alone. The choice of readline library currently prevents it:

```none
dbohdan@freebsd ~/let-go (main) [1]> gmake
which go
/usr/local/bin/go
go build -ldflags="-s -w" -o lg .
# github.com/alimpfard/line
../../go/pkg/mod/github.com/alimpfard/line@v0.0.0-20230131232016-03b4e7dee324/impl.go:284:6: undefined: setTermios
../../go/pkg/mod/github.com/alimpfard/line@v0.0.0-20230131232016-03b4e7dee324/impl.go:536:10: undefined: getTermios
../../go/pkg/mod/github.com/alimpfard/line@v0.0.0-20230131232016-03b4e7dee324/impl.go:542:6: undefined: setTermios
gmake: *** [Makefile:35: lg] Error 1
```

**Comment by nooga** [comment]
Good idea, though I don't have any BSD on hand to try it out. Could just disable readline like we do on Plan9 and call it a day. Alternatively, could look into porting alimpfard/line to BSD or finding another lightweight pure Go lib like this.

**Comment by dbohdan** [comment]
I'd be okay with either solution. You can disable the readline library on the BSDs or replace it.

Does [chzyer/readline](https://github.com/chzyer/readline) fit your criteria for a replacement? It has [few dependencies](https://github.com/chzyer/readline/blob/9dfc369f8652ba9013dadffd2d2efeada64fe44d/go.sum). I've just tried building the multiline example, and it builds and works on FreeBSD 15.0-STABLE, NetBSD 9.3, and OpenBSD 7.3.

**Comment by dbohdan** [comment]
Excellent! I can confirm it works. Cloning the repository and running `gmake` gets you a working REPL on FreeBSD 15.0-STABLE and NetBSD 9.3 ([SDF](https://sdf.org/)). On OpenBSD 7.3 ([tilde.institute](https://tilde.institute/)), `gmake` gets you a REPL with some display and input problems after you manual install recent Go. This is an EOL release of OpenBSD, so I didn't investigate further. Someone else can test on recent OpenBSD. `gmake test` passes on all three.
